name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-khwebapi-dev-southeastasia
  AZURE_WEBAPP_PACKAGE_PATH: "./dist"
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: az login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: setup dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: az logout
        run: |
          az logout
